name: Test and Build dev debug
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    needs: [ unit-tests ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build dev debug
        run: ./gradlew build
